services:
  - type: web
    name: pendaftaran-kapita-gereja
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: APP_STATUS
        value: PRODUCTION
      - key: APP_SERVER
        value: RENDER
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: '5432'
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
